name: Terraform Plan

on: [workflow_dispatch]

jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Terraform
      env:
        TERRAFORM_VERSION: "1.0.11"
      run: |
        tf_version=$TERRAFORM_VERSION
        wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
        unzip terraform_"$tf_version"_linux_amd64.zip
        sudo mv terraform /usr/local/bin/

    - name: Verify Terraform version
      run: terraform --version

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DO_ACCESS_TOKEN }}
    - name: Terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.DO_SPACES_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.DO_SPACES_SECRET_ACCESS_KEY }}
      run: terraform init

    - name: Terraform plan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.DO_SPACES_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.DO_SPACES_SECRET_ACCESS_KEY }}
        TF_VAR_do_token: ${{ secrets.DO_ACCESS_TOKEN }}
        TF_VAR_spaces_access_key_id: ${{ secrets.DO_SPACES_ACCESS_KEY_ID }}
        TF_VAR_spaces_secret_key: ${{ secrets.DO_SPACES_SECRET_ACCESS_KEY }}
      run: terraform plan